catalog/urls.py
from django.urls import path

from catalog.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    toggle_assign_to_newspaper
)

app_name = "catalog"
urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),

    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign")
    ,
]

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("catalog.urls", namespace="catalog")),
]

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item">
      <form action="{% url 'logout' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn btn-link"
               style="padding: 0; background: none; border: none; color: inherit; text-decoration: underline;">
      </form>
    </li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'catalog:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:redactor-list' %}">All redactors</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:newspaper-list' %}">All newspapers</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:topic-list' %}">All topics</a></li>
</ul>