catalog/urls.py
from django.urls import path

from catalog.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    toggle_assign_to_newspaper
)

app_name = "catalog"
urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),

    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign")
    ,
]

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("catalog.urls", namespace="catalog")),
]

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("catalog:redactor-detail", args=[str(self.id)])


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from catalog.models import Newspaper, Redactor


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )


class BaseRedactorForm(forms.ModelForm):
    def clean_years_of_experience(self):
        experience = self.cleaned_data.get("years_of_experience")
        if experience < 0:
            raise ValidationError("Years of experience cannot be negative.")
        return experience


class RedactorCreationForm(UserCreationForm, BaseRedactorForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class RedactorUpdateForm(BaseRedactorForm):
    class Meta:
        model = Redactor
        fields = ["years_of_experience"]


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic

from .forms import (
    TopicSearchForm,
    NewspaperForm,
    NewspaperSearchForm,
    RedactorUpdateForm,
    RedactorCreationForm,
    RedactorSearchForm)
from .models import Topic, Redactor, Newspaper


@login_required
def index(request):
    """View function for the home page of the site."""

    num_topics = Topic.objects.count()
    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_topics": num_topics,
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_visits": num_visits + 1,
    }

    return render(request, "catalog/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "catalog/topic_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("catalog:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("catalog:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperSearchForm(
            initial={"title": title}
        )
        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")
        form = NewspaperSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("catalog:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("catalog:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("catalog:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.all()


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("catalog:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("catalog:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("catalog:redactor-list")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    newspaper = Newspaper.objects.get(id=pk)
    if newspaper in redactor.newspapers.all():
        redactor.newspapers.remove(newspaper)
    else:
        redactor.newspapers.add(newspaper)
    return HttpResponseRedirect(
        reverse_lazy("catalog:newspaper-detail", args=[pk])
    )

templates/catalog/delete_redactor.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Redactor?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <h1 class="text-center mb-4" style="color: #2c3e50; font-family: 'Arial', sans-serif;">Welcome to the Best Newspaper
      Ever!</h1>
    <h2 class="mb-3" style="color: #34495e;">Dynamic Content</h2>
    <p class="lead mb-4" style="color: #7f8c8d;">Here are the current record counts:</p>

    <div class="card shadow-lg">
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center"
              style="background-color: #ecf0f1;">
            <strong style="color: #2980b9;">Newspapers:</strong> <span
              class="badge badge-success">{{ num_newspapers }}</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center"
              style="background-color: #ecf0f1;">
            <strong style="color: #2980b9;">Redactors:</strong> <span
              class="badge badge-success">{{ num_redactors }}</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center"
              style="background-color: #ecf0f1;">
            <strong style="color: #2980b9;">Topics:</strong> <span class="badge badge-success">{{ num_topics }}</span>
          </li>
        </ul>
      </div>
    </div>

    <p class="text-muted mt-4" style="font-size: 1.2em; color: #95a5a6;">You have visited this page {{ num_visits }}
      time{{ num_visits|pluralize }}.</p>

    <div class="text-center mt-4">
      <a href="{% url 'catalog:redactor-create' %}" class="btn btn-success btn-lg">Create New Redactor</a>
    </div>
  </div>
{% endblock %}

templates/catalog/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1 class="my-4">Delete Topic?</h1>
    <p>Are you sure you want to delete this newspaper?</p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <input type="submit" value="Yes" class="btn btn-danger">
      </div>
      <div>
        <a href="{% url 'catalog:newspaper-list' %}" class="btn btn-success">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/catalog/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container my-4">
    <h1 class="mb-4">
      {{ newspaper.title }}
      <div class="btn-group" role="group">
        <a href="{% url 'catalog:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger">
          Delete
        </a>
        <a href="{% url 'catalog:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary">
          Update
        </a>
      </div>
    </h1>

    <p class="lead">Topic:
      {% if newspaper.topic %}
        {{ newspaper.topic.name }}
      {% else %}
        No topic
      {% endif %}
    </p>

    <h2 class="mt-4">Content</h2>
    <p>{{ newspaper.content|linebreaks }}</p>

    <h3 class="mt-4">Redactors</h3>

    {% if newspaper in user.newspapers.all %}
      <a href="{% url 'catalog:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-danger mb-3">
        Remove me from this newspaper
      </a>
    {% else %}
      <a href="{% url 'catalog:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-success mb-3">
        Assign me to this newspaper
      </a>
    {% endif %}

    <hr>

    <h4 class="text-info">List of Redactors:</h4>
    <ul class="list-group">
      {% for redactor in newspaper.publishers.all %}
        <li class="list-group-item">
          {{ redactor.username }} ({{ redactor.first_name }} {{ redactor.last_name }}) -
          {{ redactor.years_of_experience }} years of experience
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/catalog/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container my-4">
    <h1 class="mb-4">{{ object|yesno:"Update,Create" }} Newspaper</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <div class="mt-3">
        <input type="submit" value="Submit" class="btn btn-success">
        <a href="{% url 'catalog:newspaper-list' %}" class="btn btn-secondary ms-2">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/catalog/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h1 class="my-4">
      Newspaper List
      <a href="{% url 'catalog:newspaper-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    <form method="get" action="" class="form-inline mb-4">
      {{ search_form|crispy }}
      <input class="btn btn-secondary" type="submit" value="🔎">
    </form>

    {% if newspaper_list %}
      <table class="table">
        <thead class="table-light">
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Topic</th>
          <th>Details</th>
        </tr>
        </thead>
        <tbody>
        {% for newspaper in newspaper_list %}
          <tr class="{% cycle 'table-primary' 'table-light' %}">
            <td>{{ newspaper.id }}</td>
            <td>{{ newspaper.title }}</td>
            <td>
              {% if newspaper.topic %}
                {{ newspaper.topic.name }}
              {% else %}
                No topic
              {% endif %}
            </td>
            <td>
              <a href="{% url 'catalog:newspaper-detail' pk=newspaper.id %}" class="btn btn-primary">View</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>There are no newspapers available.</p>
    {% endif %}
  </div>
{% endblock %}

templates/catalog/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Redactor?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  
  <a href="{% url 'catalog:redactor-list' %}" class="btn btn-secondary mt-4">Cancel</a>
{% endblock %}

templates/catalog/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container my-4">
    <h1 class="mb-4">
      Username: {{ redactor.username }}
    </h1>
    <div class="mb-3">
      <a href="{% url 'catalog:redactor-delete' pk=redactor.id %}" class="btn btn-danger me-2">
        Delete
      </a>
      <a href="{% url 'catalog:redactor-update' pk=redactor.id %}" class="btn btn-secondary">
        Update
      </a>
    </div>

    <div class="card p-4 mb-4" style="background-color: #e3f2fd; border: 1px solid #90caf9;">
      <h5 class="card-title" style="color: #0056b3;">Redactor Details</h5>
      <p><strong>First name:</strong> {{ redactor.first_name }}</p>
      <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
      <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
      <p><strong>Is staff:</strong> {{ redactor.is_staff|yesno:"Yes,No" }}</p>
    </div>

    <h4 class="mb-3" style="color: #007bff;">Newspapers</h4>
    {% if redactor.newspapers.all %}
      <div class="list-group">
        {% for newspaper in redactor.newspapers.all %}
          <div class="list-group-item">
            <h5 class="mb-1" style="color: #343a40;">{{ newspaper.title }}</h5>
            <p class="mb-1"><strong>Published Date:</strong> {{ newspaper.published_date }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ newspaper.id }}</p>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>No newspapers!</p>
    {% endif %}
  </div>
{% endblock %}

templates/catalog/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container my-4">
    <h1 class="text-center mb-4">Create Redactor</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      <div class="card p-4">
        {{ form|crispy }}
        <div class="d-flex justify-content-between mt-4">
          <input type="submit" value="Submit" class="btn btn-success">
          <a href="{% url 'catalog:redactor-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

templates/catalog/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container my-4">
    <h1 class="mb-4">
      Redactor List
      <a href="{% url 'catalog:redactor-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    <form method="get" action="" class="form-inline mb-4">
      {{ search_form|crispy }}
      <input class="btn btn-secondary" type="submit" value="🔎">
    </form>

    {% if redactor_list %}
      <table class="table table-striped table-hover">
        <thead class="table-light">
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Years of Experience</th>
        </tr>
        </thead>
        <tbody>
        {% for redactor in redactor_list %}
          <tr class="{% cycle 'table-primary' 'table-light' %}">
            <td>{{ redactor.id }}</td>
            <td>
              <a href="{{ redactor.get_absolute_url }}" class="text-info">
                {{ redactor.username }} {% if user == redactor %} (Me){% endif %}
              </a>
            </td>
            <td>{{ redactor.first_name }}</td>
            <td>{{ redactor.last_name }}</td>
            <td>{{ redactor.years_of_experience }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="alert alert-warning" role="alert">
        There are no redactors in the system.
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/catalog/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1 class="my-4">Delete Topic?</h1>
    <p>Are you sure you want to delete this topic?</p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <input type="submit" value="Yes" class="btn btn-danger">
      </div>
      <div>
        <a href="{% url 'catalog:topic-list' %}" class="btn btn-success">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/catalog/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h1 class="my-4">{{ object|yesno:"Update,Create" }} Topic</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <div class="mt-3">
        <input type="submit" value="Submit" class="btn btn-primary">
      </div>
    </form>
  </div>
{% endblock %}

templates/catalog/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h1 class="my-4">Topic List</h1>
    <div class="mb-3">
      <a href="{% url 'catalog:topic-create' %}" class="btn btn-primary">Create Topic</a>
    </div>
    <form method="get" action="" class="form-inline mb-4">
      {{ search_form|crispy }}
      <button class="btn btn-secondary ml-2" type="submit">🔎</button>
    </form>

    {% if topic_list %}
      <table class="table">
        <thead class="{% cycle 'table-light' 'table-info' %}">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for topic in topic_list %}
          <tr class="{% cycle 'table-light' 'table-info' %}">
            <td>{{ topic.id }}</td>
            <td>{{ topic.name }}</td>
            <td>
              <a class="btn btn-warning btn-sm" href="{% url 'catalog:topic-update' pk=topic.id %}">Update</a>
              <a class="btn btn-danger btn-sm" href="{% url 'catalog:topic-delete' pk=topic.id %}">Delete</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="alert alert-info" role="alert">
        There are no topics available.
      </div>
    {% endif %}
  </div>
{% endblock %}